# Generated by Django 3.2 on 2021-04-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='slug',
        ),
        migrations.AlterField(
            model_name='file',
            name='subject',
            field=models.TextField(),
        ),
    ]
